_test42/main/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('',
    url(r'^requests/$', '_test42.main.views.request_log', name='request_log'),
    url(r'^request_delete/$', '_test42.main.views.delete_request_log',
        name='request_log_delete'),
    url(r'^edit/(?P<profile_id>[^/]+)/$', '_test42.main.views.profile_edit', \
        name='profile_edit'),
    url(r'^$', '_test42.main.views.profile', name='profile'),
)

_test42/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '_test42.views.home', name='home'),
    # url(r'^_test42/', include('_test42.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', \
        name='login_page'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', \
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('_test42.main.urls')),
)

_test42/main/models.py
# coding=utf-8
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


def _log_action(model_name, action):
    changes_log = ModelChangesLog(name=model_name, action=action)
    changes_log.save()

    return changes_log


@receiver(post_save)
def model_post_save(sender, instance, created, **kwargs):
    model_name = sender.__name__

    if 'django.contrib' not in sender.__module__ \
    and model_name not in ['ModelChangesLog', 'MigrationHistory']:
        action = 'create' if created else 'edit'

        _log_action(model_name, action)


@receiver(post_delete)
def model_post_delete(sender, instance, **kwargs):
    model_name = sender.__name__
    if model_name != 'ModelChangesLog':

        _log_action(model_name, 'delete')


class Profile(models.Model):

    name = models.CharField('Name', max_length=256)
    surname = models.CharField('Surname', max_length=256)
    birth_date = models.DateField('Date of birth')
    bio = models.TextField('Bio')

    email = models.EmailField()
    jabber = models.CharField(max_length=256)
    skype = models.IntegerField()
    other = models.TextField()

    photo = models.ImageField(upload_to='photos/%Y/%m/%d', \
                              null=True, blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.name, self.surname)


class RequestLog(models.Model):

    method = models.CharField(max_length=40)
    url = models.CharField(max_length=256)
    remote_addr = models.CharField(max_length=60, null=True, blank=True)
    datetime = models.DateTimeField(auto_now=True, auto_now_add=True)

    order = models.IntegerField(default=0)


class ModelChangesLog(models.Model):

    name = models.CharField(max_length=100)
    action = models.CharField(max_length=40)
    datetime = models.DateTimeField(auto_now=True, auto_now_add=True)

_test42/main/forms.py
from django import forms


from _test42.main.models import Profile
from _test42.main.widgets import CalendarWidget


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        widgets = {
            'bio': forms.Textarea(attrs={'cols': 40, 'rows': 10}),
            'other': forms.Textarea(attrs={'cols': 40, 'rows': 10}),
            'birth_date': CalendarWidget()
        }

_test42/main/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import simplejson

from _test42.main.models import Profile, RequestLog
from _test42.main.forms import ProfileEditForm


def profile(request):
    profile = Profile.objects.all()[0]

    return render(request, 'profile.html', {'profile': profile})


@login_required
def profile_edit(request, profile_id=None):
    if not profile_id.isdigit():
        raise Http404

    _is_ajax = request.is_ajax()

    profile = get_object_or_404(Profile, id=int(profile_id))
    if request.POST:
        form = ProfileEditForm(data=request.POST, \
                               files=request.FILES, \
                               instance=profile)

        _is_valid = form.is_valid()
        if _is_valid:
            form.save()

        if not _is_ajax and _is_valid:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', \
                    reverse('profile_edit', kwargs={'profile_id': profile.id})
                ))

        if _is_ajax:
            response_data = {}
            if not _is_valid:
                response_data['errors'] = form.errors
            return HttpResponse(simplejson.dumps(response_data), \
                                mimetype="application/json")

    else:
        form = ProfileEditForm(instance=profile)

    return render(request, 'profile_edit.html', {'form': form})


def request_log(request):
    request_logs = RequestLog.objects.order_by('-order', 'id')[:10]
    request_logs = list(request_logs)

    return render(request, 'request_log.html', {'request_logs': request_logs})


def delete_request_log(request):
    if not request.POST and 'entry_id' not in request.POST:
        raise Http404
    entry_id = request.POST['entry_id']

    entry = get_object_or_404(RequestLog, id=int(entry_id))
    entry.delete()

    return HttpResponse(simplejson.dumps({'entry_id': entry_id}), \
                        mimetype="application/json")

_test42/main/templates/base.html
<html>
	<head>
		<title>42 Coffee Cups Test Assignment</title>
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
		{% block extrahead %}
		{% endblock %}		
	</head>
	<body>
		{% block content %}
		{% endblock %}
		{% block scripts %}
		{% endblock %}
	</body>
</html>

_test42/main/templates/profile.html
{% extends "base.html" %}
{% load edit_link %}

{% block content %}
<h1>42 Coffee Cups Test Assignment</h1>
<a href="{% url profile_edit profile_id=profile.id %}">Edit</a> {% edit_link profile %}
<table>
	<tr>
		<td>Personal data</td><td colspan="2">Contacts</td>
	</tr>
	<tr>
		<td>{{ profile.name }}</td><td>Email:</td><td>{{ profile.email }}</td>
	</tr>
	<tr>
		<td>{{ profile.surname }}</td><td>Jabber:</td><td>{{ profile.jabber }}</td>
	</tr>
	<tr>
		<td>{{ profile.birth_date }}</td><td>Skype:</td><td>{{ profile.skype }}</td>
	</tr>
	<tr>
		<td>Photo:</td><td colspan="2">Bio:</td>
	</tr>
	<tr>
		<td rowspan="3">
			<img src="{% if profile.photo %}{{ profile.photo.url }}{% endif %}" width="230" height="320" />
		</td>
		<td colspan="2" valign="top">{{ profile.bio }}</td>
	</tr>
	<tr>
		<td colspan="2">Other contacts:</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">{{ profile.other }}</td>
	</tr>
	
</table>
<hr/>

<a href="{% url request_log %}">requests</a>
{% endblock %}

_test42/main/templates/profile_edit.html
{% extends "base.html" %}

{% block extrahead %}
	{{ form.media }}
	<style>
		.el_error {border-color: red}
		.error_message {color: red}
	</style>
{% endblock %}

{% block content %}
<h1>42 Coffee Cups Test Assignment</h1>

<div id="form_errors">
{% if form.errors %}
	{{ form.errors }}
{% endif %}
</div>

<form id="profile_edit_form" method="post" action="{% url profile_edit profile_id=form.initial.id %}" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		<tr>
			<td colspan="2">Personal data</td><td colspan="2">Contacts</td>
		</tr>
		<tr>
			<td>Name:</td><td>{{ form.name }}</td>
			<td>Email:</td><td>{{ form.email }}</td>
		</tr>
		<tr>
			<td>Last name:</td><td>{{ form.surname }}</td>
			<td>Jabber:</td><td>{{ form.jabber }}</td>
		</tr>
		<tr>
			<td>Date of birth:</td><td>{{ form.birth_date }}</td>
			<td>Skype:</td><td>{{ form.skype }}</td>
		</tr>
		<tr>
			<td>Photo:</td><td>{{ form.photo }}</td>
			<td colspan="2">Bio:</td>
		</tr>
		<tr>
			<td colspan="2" rowspan="3">
				
				<img id="photo_preview" src="{% if form.initial.photo %}{{ form.initial.photo.url }}{% endif %}" width="230" height="320" />
				
			</td>
			<td colspan="2">{{ form.bio }}</td>
		</tr>
		<tr>
			<td colspan="2">Other contacts:</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.other }}</td>
		</tr>
	</table>
	<div class="progress"></div>
	<input type="submit" value="Submit" /> <a href="/">Cancel</a>
</form>
<hr/>
{% endblock %}

{% block scripts %}
	{{ block.super }}
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.form.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){ 
			$('#id_photo').on('change', function(){
				if (this.files && this.files[0]){
					var reader = new FileReader();
					reader.onload = function(e){
						$('#photo_preview').attr('src', e.target.result);
					};
					reader.readAsDataURL(this.files[0]);
				}
			});
			
			var progress = $('.progress');

			var controls = $('input, textarea');
			
			controls.on('keypress', function(){
				progress.hide();
			});
			
			$('#profile_edit_form').ajaxForm({
				beforeSend: function(){
					controls.attr('disabled', true).removeClass('el_error');
					$('.error_message').remove();
					progress.text('Sending...');
				},
				success: function(){
					controls.attr('disabled', false);
					progress.text('Sucess');
				},
				complete: function(resp){
					var resp_data = $.parseJSON(resp.responseText);
					if (resp_data.errors !== undefined){
						$.each(resp_data.errors, function(name, message){
							progress.text('Error');
							
							var el = $('[name='+name+']').addClass('el_error');
							el.parent().append('<span class="error_message">'+message+'</span>');
						});
					} else {
						setTimeout(function(){ progress.text('') }, 2000);
					}
				}
			});
		});
	</script>
{% endblock %}

_test42/main/templates/profile_edit_errors.html
{% if form.errors %}
	{{ form.errors }}
{% endif %}

_test42/main/templates/request_log.html
{% extends "base.html" %}

{% block content %}
{% csrf_token %}
<table>
	<tr>
		<td>DateTime</td><td>Method</td><td>Url</td><td>Order</td><td>*</td>
	</tr>
	{% for r in request_logs %}
	<tr id="request_log_{{ r.id }}">
		<td>{{ r.datetime|date:'Y-m-d H:i' }}</td><td>{{ r.method }}</td>
		<td>{{ r.url }}</td><td>{{ r.order }}</td>
		<td>
			<a href="{% url request_log_delete %}" class="js_delete" entry="{{ r.id }}">Delete</a>
		</td>
	</tr>
	{% endfor %}
</table>

<hr />

<a href="{% url profile%}">profile</a>
{% endblock %}

{% block scripts %}
	{{ block.super }}
	<script type="text/javascript" src="{{ STATIC_URL }}js/requests.js"></script>
{% endblock %}